name: Node CI

on:
  pull_request: # auto-build on PR request against master branch 
    branches: 
      - master
  push: # auto-build on merge to master branch
    branches: 
      - master 
          

jobs:
  build:
    name: build process for PR against master branch 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
      env:
        CI: true
  
